MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet101_conv5_body
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.00125
  GAMMA: 0.1
  MAX_ITER: 200000
  STEPS: [0, 75000, 150000]  #4000 8000
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  #IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/X-101-32x8d.pkl'
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/COCO-mask-X-101-32x8d.pkl'
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 32
  WIDTH_PER_GROUP: 8
  RES5_DILATION: 2
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7  
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  SCALES: (800, 900, 1000, 1100, 1200, 1300)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 5000
  BBOX_THRESH: 0.7
  RPN_NMS_THRESH: 0.8
TEST:
  SCALE: 1300
  MAX_SIZE: 1333
  NMS: 0.35
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  FORCE_JSON_DATASET_EVAL: True
  DETECTIONS_PER_IM: 1000
  SCORE_THRESH: 0.99
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.6
#  SOFT_NMS:
#    ENABLED: True
    # See soft NMS paper for definition of these options
#    METHOD: 'linear'
#    SIGMA: 0.5
#  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
#  RPN_POST_NMS_TOP_N: 1000
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION
    COORD_HEUR: UNION
    H_FLIP: True
    V_FLIP: False
    ROTATION90: False
    SCALES: (800, 900, 1000, 1100, 1200)
    MAX_SIZE: 2000  # 2000
    SCALE_H_FLIP: True
    SCALE_V_FLIP: False
    SCALE_ROTATION90: False
    SCALE_SIZE_DEP: False
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
